### ISSUE TITLE
www.gta5-mods.com 

### ISSUE THREAD

**Issue by ReverentMouse** [fr-Pursuit/GTAVModdingLauncher#10]
---- GTA V Modding Launcher 0.5.5 crash report ----
Generated on 13/08/2016 23:43:18

-- Thrown exception --
System.MissingMethodException: Method not found: '!!0[] System.Array.Empty()'.
   at GTAVModdingLauncher.Launcher.InitLauncher()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

-- Launcher state --
Is initialized: True
Is window initialized: True

-- UI state --
Selected profile index: 0
Selected profile: ~Unexpected error~
Is working: False
Are buttons enabled: False

**Comment by fr-Pursuit** [comment]
Please install .NET Framework 4.6
