### ISSUE TITLE
Modding launcher crash after changing GTA location

### ISSUE THREAD

**Issue by nak0604** [fr-Pursuit/GTAVModdingLauncher#17]
---- GTA V Modding Launcher 0.5.5 crash report ----
Generated on 19/10/2016 01:55:53

-- Thrown exception --
System.InvalidOperationException: The calling thread cannot access this object because a different thread owns it.
   at System.Windows.Threading.Dispatcher.VerifyAccess()
   at System.Windows.Window.get_CriticalHandle()
   at System.Windows.MessageBox.Show(Window owner, String messageBoxText, String caption, MessageBoxButton button, MessageBoxImage icon)
   at GTAVModdingLauncher.Messages.GTANotFound()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

-- Launcher state --
Is initialized: True
Is window initialized: True

-- UI state --
Selected profile index: 0
Selected profile: ~Unexpected error~
Is working: False
Are buttons enabled: False

**Comment by fr-Pursuit** [comment]
GTA can't work if you change its location without telling it where it is. You either need to move it using the installer (if it's possible), or to reinstall it. The launcher shouldn't crash though, but instead show you an error message. Thanks for letting me know that.
