### ISSUE TITLE
GTA V Modding Launcher 0.5.6 crash report

### ISSUE THREAD

**Issue by darrienjw** [fr-Pursuit/GTAVModdingLauncher#26]
Here's the crash report for the launcher. Any help is appreciated.

---- GTA V Modding Launcher 0.5.6 crash report ----
Generated on 24/02/2017 16:12:27

-- Thrown exception --
System.InvalidOperationException: The calling thread cannot access this object because a different thread owns it.
   at System.Windows.Threading.Dispatcher.VerifyAccess()
   at System.Windows.Window.get_CriticalHandle()
   at System.Windows.MessageBox.Show(Window owner, String messageBoxText, String caption, MessageBoxButton button, MessageBoxImage icon)
   at GTAVModdingLauncher.Messages.GTANotFound()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

-- Launcher state --
Is initialized: True
Is window initialized: True

-- UI state --
Selected profile index: 0
Selected profile: ~Unexpected error~
Is working: False
Are buttons enabled: False

**Comment by fr-Pursuit** [comment]
This issue will be fixed in the next version. In the meantime, to use the launcher, please make sure it can find your GTA path.

Please note that it doesn't work with cracked versions of the game.

**Comment by darrienjw** [comment]
The path is in the default location since I only installed GTA recently. The launcher isn't picking it up.

I'm also not using a cracked version. I bought and downloaded the game via Social Club.

**Comment by fr-Pursuit** [comment]
I reopen the issue since you will probably still have issues in the new update (except it won't crash but instead say your GTA wasn't found).

You need to create an entry in your registry with RegEdit.exe. Please create the "HKey Local Machine\SOFTWARE\Wow6432Node\Rockstar Games\Grand Theft Auto V" subkey, then add a value of type REG_SZ (aka string) called "InstallFolder" that contains the installation folder path.

It should fix your issue.

**Comment by fr-Pursuit** [comment]
Version 0.6.0 allows you to specify a custom installation.
Your problem should therefore be fixed.
