### ISSUE TITLE
it will not start

### ISSUE THREAD

**Issue by ctriggergg** [fr-Pursuit/GTAVModdingLauncher#3]
i need help it just wont start

--- GTA V Modding Launcher 0.5.5 crash report ----
Generated on 27/07/2016 21:34:52

crash report

-- Thrown exception --
System.MissingMethodException: Method not found: '!!0[] System.Array.Empty()'.
   at GTAVModdingLauncher.Launcher.InitLauncher()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

-- Launcher state --
Is initialized: True
Is window initialized: True

-- UI state --
Selected profile index: 0
Selected profile: ~Unexpected error~
Is working: False
Are buttons enabled: False

**Comment by fr-Pursuit** [comment]
Please make sure you have .NET framework 4.6. If thats

**Comment by fr-Pursuit** [comment]
Please make sure you have .NET Framework 4.6. If that's the case, reinstall it.
