### ISSUE TITLE
Mod not loading

### ISSUE THREAD

**Issue by vineeth3696** [fr-Pursuit/GTAVModdingLauncher#8]
-- GTA V Modding Launcher 0.5.5 crash report ----
Generated on 03-08-2016 21:04:53

-- Thrown exception --
System.MissingMethodException: Method not found: '!!0[] System.Array.Empty()'.
   at GTAVModdingLauncher.Launcher.InitLauncher()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

-- Launcher state --
Is initialized: True
Is window initialized: True

-- UI state --
Selected profile index: 0
Selected profile: ~Unexpected error~
Is working: False
Are buttons enabled: False

**Comment by fr-Pursuit** [comment]
You need .NET framework 4.6 to use the launcher. If you already have it, reinstall it.
